# SPDX-FileCopyrightText: 2020 Intel Corporation
#
# SPDX-License-Identifier: MIT

name: build_all_offline_apt_dnf_scheduled

on:
  push: {}
  workflow_dispatch: {}
  schedule:
    - cron: '0 0 * * *'

env:
  WINDOWS_BASEKIT_URL: https:/registrationcenter-download.intel.com/akdlm/IRC_NAS/c961e083-5685-4f0b-ada5-c6cf16f561dd/w_BaseKit_p_2023.1.0.47256_offline.exe
  WINDOWS_HPCKIT_URL: https:/registrationcenter-download.intel.com/akdlm/IRC_NAS/2a13d966-fcc5-4a66-9fcc-50603820e0c9/w_HPCKit_p_2023.1.0.46357_offline.exe
  WINDOWS_IOTKIT_URL: https:/registrationcenter-download.intel.com/akdlm/IRC_NAS/365570df-0a47-463b-b1eb-cda0c2e04bc6/w_IoTKit_p_2023.1.0.46355_offline.exe
  WINDOWS_RENDERKIT_URL: https:/registrationcenter-download.intel.com/akdlm/IRC_NAS/62054265-968e-4c68-88dd-c1a06861dba2/w_RenderKit_p_2023.1.0.47568_offline.exe
  LINUX_BASEKIT_URL: https:/registrationcenter-download.intel.com/akdlm/IRC_NAS/7deeaac4-f605-4bcf-a81b-ea7531577c61/l_BaseKit_p_2023.1.0.46401_offline.sh
  LINUX_HPCKIT_URL: https:/registrationcenter-download.intel.com/akdlm/IRC_NAS/1ff1b38a-8218-4c53-9956-f0b264de35a4/l_HPCKit_p_2023.1.0.46346_offline.sh
  LINUX_IOTKIT_URL: https:/registrationcenter-download.intel.com/akdlm/IRC_NAS/c1cb379a-6aab-4f18-a8c9-611ca8905ef8/l_IoTKit_p_2023.1.0.46344_offline.sh
  LINUX_AIKIT_URL: https://registrationcenter-download.intel.com/akdlm/irc_nas/19090/l_AIKit_p_2023.0.0.26100_offline.sh
  LINUX_DLFDKIT_URL: https:/registrationcenter-download.intel.com/akdlm/IRC_NAS/a7f1659f-558b-4131-a839-ab5ff2584c77/l_DLFDKit_p_2023.1.0.46364_offline.sh
  LINUX_RENDERKIT_URL: https:/registrationcenter-download.intel.com/akdlm/IRC_NAS/79e1d29b-1546-4795-b2a4-ae5f8d504df2/l_RenderKit_p_2023.1.0.47259_offline.sh
  MACOS_BASEKIT_URL: https:/registrationcenter-download.intel.com/akdlm/IRC_NAS/2516a0a0-de4d-4f3d-9e83-545b32127dbb/m_BaseKit_p_2023.1.0.45568_offline.dmg
  MACOS_HPCKIT_URL: https:/registrationcenter-download.intel.com/akdlm/IRC_NAS/a99cb1c5-5af6-4824-9811-ae172d24e594/m_HPCKit_p_2023.1.0.44543_offline.dmg
  MACOS_RENDERKIT_URL: https:/registrationcenter-download.intel.com/akdlm/IRC_NAS/da33ae67-fcf0-4b4d-8e41-a4b31e9b49fd/m_RenderKit_p_2023.1.0.47135_offline.dmg
  LINUX_COMPONENTS: intel-oneapi-compiler-dpcpp-cpp-and-cpp-classic,intel-oneapi-compiler-fortran
  SAMPLES_TAG: 2023.1.0

jobs:
  build_windows_base_offline:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - name: tracert
      run: tracert -h 1 registrationcenter-download.intel.com
    - name: install_basekit
      run: scripts/install_windows.bat $WINDOWS_BASEKIT_URL intel.oneapi.win.dpcpp-compiler
    - name: build_dpc++
      run: scripts/build_windows.bat dpc++ 2022 $SAMPLES_TAG

    # Delete the following if you don't want to save install logs
    - name: Saving install logs
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: InstallLogs_${{ github.job }}
        path: |
          extract.log
          bootstrapper*
          installer*
        retention-days: 7

  build_windows_hpc_iot_offline:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - name: tracert
      run: tracert -h 1 registrationcenter-download.intel.com
    - name: install_hpckit
      run: scripts/install_windows.bat $WINDOWS_HPCKIT_URL intel.oneapi.win.ifort-compiler
    - name: install_iotkit
      run: scripts/install_windows.bat $WINDOWS_IOTKIT_URL intel.oneapi.win.cpp-compiler
    - name: build_c++
      run: scripts/build_windows.bat c++ 2022 $SAMPLES_TAG
    - name: build_fortran
      run: scripts/build_windows.bat fortran 2022 $SAMPLES_TAG

    # Delete the following if you don't want to save install logs
    - name: Saving install logs
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: InstallLogs_${{ github.job }}
        path: |
          extract.log
          bootstrapper*
          installer*
        retention-days: 7

  build_windows_render_offline:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - name: tracert
      run: tracert -h 1 registrationcenter-download.intel.com
    - name: install_renderkit
      run: scripts/install_windows.bat $WINDOWS_RENDERKIT_URL intel.oneapi.win.embree

    # Delete the following if you don't want to save install logs
    - name: Saving install logs
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: InstallLogs_${{ github.job }}
        path: |
          extract.log
          bootstrapper*
          installer*
        retention-days: 7

  build_linux_all_offline:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - name: traceroute
      run: |
        sudo apt-get install -y traceroute
        sudo traceroute --tcp registrationcenter-download.intel.com
    - name: install_basekit
      run: scripts/install_linux.sh $LINUX_BASEKIT_URL intel.oneapi.lin.dpcpp-cpp-compiler
    - name: install_hpckit
      run: scripts/install_linux.sh $LINUX_HPCKIT_URL intel.oneapi.lin.ifort-compiler
    - name: install_iotkit
      run: scripts/install_linux.sh $LINUX_IOTKIT_URL intel.oneapi.lin.dpcpp-cpp-compiler-pro
    - name: build_c++
      run: scripts/build_linux.sh c++ $SAMPLES_TAG
    - name: build_fortran
      run: scripts/build_linux.sh fortran $SAMPLES_TAG
    - name: build_dpcpp
      run: scripts/build_linux.sh dpc++ $SAMPLES_TAG

    # Delete the following if you don't want to save install logs
    - name: Saving install logs
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: InstallLogs_${{ github.job }}
        path: |
          bootstrapper*
          installer*
        retention-days: 7

  build_linux_all_offline_2:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - name: traceroute
      run: |
        sudo apt-get install -y traceroute
        sudo traceroute --tcp registrationcenter-download.intel.com
    - name: install_aikit
      run: scripts/install_linux.sh $LINUX_AIKIT_URL intel.oneapi.lin.tensorflow
    - name: install_dlfdkit
      run: scripts/install_linux.sh $LINUX_DLFDKIT_URL intel.oneapi.lin.ccl.devel
    - name: install_renderkit
      run: scripts/install_linux.sh $LINUX_RENDERKIT_URL intel.oneapi.lin.embree

    # Delete the following if you don't want to save install logs
    - name: Saving install logs
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: InstallLogs_${{ github.job }}
        path: |
          bootstrapper*
          installer*
        retention-days: 7

  build_linux_apt:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - name: setup apt repo
      run: |
        sudo dpkg --add-architecture i386
        scripts/setup_apt_repo_linux.sh
        grep ^ /etc/apt/sources.list /etc/apt/sources.list.d/*
    - name: print packages info
      run: sudo apt-cache show python3 python-jsonschema intel-oneapi-*
    - name: print info2
      run: sudo apt-cache depends intel-oneapi-runtime-libs
    - name: dry-run install oneapi
      run: sudo apt install --dry-run $(apt-cache search intel-oneapi | grep -v intelfpga | grep -v intel-oneapi-ilit | grep -v intel-oneapi-lpot | grep -v -- '-tail$' | awk '{print $1}')
    - name: dry-run install mpi
      run: sudo apt install --dry-run $(apt-cache search intel-mpi | grep -v intel-mpi-2019.0-045 | grep -v -- '-tail$' | awk '{print $1}')
    - name: install
      run: scripts/install_linux_apt.sh $LINUX_COMPONENTS
    - name: build
      run: scripts/build_linux.sh c++ $SAMPLES_TAG
    - name: build
      run: scripts/build_linux.sh fortran $SAMPLES_TAG
    - name: build
      run: scripts/build_linux.sh dpc++ $SAMPLES_TAG

  build_linux_apt_toolkits:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - name: setup apt repo
      run: scripts/setup_apt_repo_linux.sh
    - name: sudo apt update
      run: sudo apt update
    - name: print packages info
      run: sudo apt-cache show intel-oneapi-*
    - name: dry-run install basekit
      run: sudo apt install --dry-run intel-basekit
      if: ${{ always() }}
    - name: dry-run install hpckit
      run: sudo apt install --dry-run intel-hpckit
      if: ${{ always() }}
    - name: dry-run install iotkit
      run: sudo apt install --dry-run intel-iotkit
      if: ${{ always() }}
    - name: dry-run install aikit
      run: sudo apt install --dry-run intel-aikit
      if: ${{ always() }}
    - name: dry-run install dlfdkit
      run: sudo apt install --dry-run intel-dlfdkit
      if: ${{ always() }}
    - name: dry-run install renderkit
      run: sudo apt install --dry-run intel-renderkit
      if: ${{ always() }}
    # - name: dry-run install FPGA1
      # run: sudo apt install --dry-run intel-oneapi-intelfpgadpcpp-a10gx-s10sx
      # if: ${{ always() }}
    # - name: dry-run install FPGA2
      # run: sudo apt install --dry-run intel-oneapi-intelfpgadpcpp-a10gx-s10sx-quartus
      # if: ${{ always() }}
    - name: dry-run install FPGA3
      run: sudo apt install --dry-run intel-oneapi-intelfpgadpcpp-custom-platforms-quartus19.4
      if: ${{ always() }}
    - name: dry-run install FPGA4
      run: sudo apt install --dry-run intel-oneapi-intelfpgadpcpp-custom-platforms-quartus20.2
      if: ${{ always() }}
    - name: dry-run install FPGA5
      run: sudo apt install --dry-run intel-oneapi-intelfpgadpcpp-custom-platforms-quartus20.3
      if: ${{ always() }}
    - name: dry-run install FPGA6
      run: sudo apt install --dry-run intel-oneapi-intelfpgadpcpp-custom-platforms-quartus20.4
      if: ${{ always() }}
    - name: install
      run: scripts/install_linux_apt.sh $LINUX_COMPONENTS
    - name: build
      run: scripts/build_linux.sh c++ $SAMPLES_TAG
    - name: build
      run: scripts/build_linux.sh fortran $SAMPLES_TAG
    - name: build
      run: scripts/build_linux.sh dpc++ $SAMPLES_TAG

  build_linux_dnf:
    runs-on: ubuntu-20.04
    container: fedora
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - name: setup yum/dnf repo
      run: scripts/setup_yum_dnf_repo_linux.sh
    - name: install prerequisites
      run: sudo dnf -y install git make gcc g++ findutils procps cmake
    - name: install
      run: scripts/install_linux_dnf.sh $LINUX_COMPONENTS
    - name: install mpi
      run: sudo dnf -y install intel-mpi
    - name: build
      run: scripts/build_linux.sh c++ $SAMPLES_TAG
    - name: build
      run: scripts/build_linux.sh fortran $SAMPLES_TAG
    - name: build
      run: scripts/build_linux.sh dpc++ $SAMPLES_TAG

  build_macos_all_offline:
    runs-on: macos-latest
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - name: install_basekit
      run: scripts/install_macos.sh $MACOS_BASEKIT_URL
    - name: install_hpckit
      run: scripts/install_macos.sh $MACOS_HPCKIT_URL
    - name: install_renderkit
      run: scripts/install_macos.sh $MACOS_RENDERKIT_URL
    - name: build_c++
      run: scripts/build_macos.sh c++ $SAMPLES_TAG
    - name: build_fortran
      run: scripts/build_macos.sh fortran $SAMPLES_TAG

    # Delete the following if you don't want to save install logs
    - name: Saving install logs
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: InstallLogs_${{ github.job }}
        path: |
          bootstrapper*
          installer*
        retention-days: 7
