name: build_macos_cpp

on:
  push

jobs:
  build:
    runs-on: macos-latest
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - name: build_macos_cpp
      run: |
        curl --output m_hpckit.dmg --url https://registrationcenter-download.intel.com/akdlm/irc_nas/16865/m_HPCKit_b_2021.1.8.1885.dmg
        hdiutil attach m_hpckit.dmg
        sudo /Volumes/m_HPCKit_b_2021.1.8.1885/bootstrapper.app/Contents/MacOS/bootstrapper -s --action install --components=intel.oneapi.mac.cpp-compiler --eula=accept --continue-with-optional-error=yes
        cd src/c++
        source /opt/intel/oneapi/setvars.sh
        make -f Makefile.macos
        