# SPDX-FileCopyrightText: 2020 Intel Corporation
#
# SPDX-License-Identifier: MIT

name: test

on:
  push: {}
  workflow_dispatch: {}

env:
  WINDOWS_BASEKIT_URL: https://registrationcenter-download.intel.com/akdlm/irc_nas/19078/w_BaseKit_p_2023.0.0.25940_offline.exe
  WINDOWS_HPCKIT_URL: https://registrationcenter-download.intel.com/akdlm/irc_nas/19085/w_HPCKit_p_2023.0.0.25931_offline.exe
  WINDOWS_IOTKIT_URL: https://registrationcenter-download.intel.com/akdlm/irc_nas/19083/w_IoTKit_p_2023.0.0.25928_offline.exe
  WINDOWS_RENDERKIT_URL: https://registrationcenter-download.intel.com/akdlm/irc_nas/19089/w_RenderKit_p_2023.0.0.25942_offline.exe
  LINUX_BASEKIT_URL: https://registrationcenter-download.intel.com/akdlm/irc_nas/19079/l_BaseKit_p_2023.0.0.25537_offline.sh
  LINUX_HPCKIT_URL: https://registrationcenter-download.intel.com/akdlm/irc_nas/19084/l_HPCKit_p_2023.0.0.25400_offline.sh
  LINUX_IOTKIT_URL: https://registrationcenter-download.intel.com/akdlm/irc_nas/19082/l_IoTKit_p_2023.0.0.25397_offline.sh
  LINUX_AIKIT_URL: https://registrationcenter-download.intel.com/akdlm/irc_nas/19090/l_AIKit_p_2023.0.0.26100_offline.sh
  LINUX_DLFDKIT_URL: https://registrationcenter-download.intel.com/akdlm/irc_nas/19081/l_DLFDKit_p_2023.0.0.25405_offline.sh
  LINUX_RENDERKIT_URL: https://registrationcenter-download.intel.com/akdlm/irc_nas/19087/l_RenderKit_p_2023.0.0.25403_offline.sh
  MACOS_BASEKIT_URL: https://registrationcenter-download.intel.com/akdlm/irc_nas/19080/m_BaseKit_p_2023.0.0.25441_offline.dmg
  MACOS_HPCKIT_URL: https://registrationcenter-download.intel.com/akdlm/irc_nas/19086/m_HPCKit_p_2023.0.0.25440_offline.dmg
  MACOS_RENDERKIT_URL: https://registrationcenter-download.intel.com/akdlm/irc_nas/19088/m_RenderKit_p_2023.0.0.25438_offline.dmg
  LINUX_COMPONENTS: intel-oneapi-compiler-dpcpp-cpp-and-cpp-classic,intel-oneapi-compiler-fortran
  SAMPLES_TAG: 2023.0.0

jobs:
  build_linux_apt_all:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - name: setup apt repo
      run: |
        sudo dpkg --add-architecture i386
        scripts/setup_apt_repo_linux.sh
        grep ^ /etc/apt/sources.list /etc/apt/sources.list.d/*
    - name: apt install/remove oneapi one by one
      run: apt-cache search intel-oneapi | grep -v intelfpga | grep -v intel-oneapi-ilit | grep -v intel-oneapi-lpot | grep -v -- '-tail$' | grep -e 2022.3 -e 2022.2 | awk '{print $1}' | xargs -t -I % sh -c 'sudo apt install -y %; tree /opt/intel; sudo apt remove -y %'

  build_linux_dnf_all:
    runs-on: ubuntu-20.04
    container: fedora
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - name: setup yum/dnf repo
      run: scripts/setup_yum_dnf_repo_linux.sh
    - name: install prerequisites
      run: sudo dnf -y install git make gcc g++
    - name: install/remove oneapi one by one
      run: sudo dnf -y --disablerepo="*" --enablerepo="oneAPI" list available | grep -v -- '-tail$' | awk '{print $1}' | grep -e 2022.3 -e 2022.2 | xargs -t -I % sh -c 'sudo dnf install -y %; tree /opt/intel; sudo dnf remove -y %'
